# Generated by Django 4.2.1 on 2023-05-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('rate', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(default='сом', max_length=10)),
                ('productivity', models.CharField(max_length=20)),
                ('unit', models.IntegerField(default=0)),
                ('unitName', models.CharField(choices=[('g', 'gram'), ('kg', 'kilograms'), ('liter', 'liter')], default='g', max_length=50)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
