# Generated by Django 4.2.1 on 2023-06-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_name',
            new_name='user',
        ),
    ]
