# Generated by Django 4.2.1 on 2023-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2, verbose_name='Средний рейтинг'),
        ),
    ]
