# Generated by Django 4.2.1 on 2023-05-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitName',
            field=models.CharField(choices=[('гр', 'грамм'), ('кг', 'килограмм'), ('литер', 'литер'), ('шт', 'штук')], default='гр', max_length=50),
        ),
    ]
